profile: "uni"
version: 1

global:
  delimiter: ","
  encoding: "auto"
  deduplicate:
    enabled: false
    subset: []
    ignore_empty_in_subset: true
  logging:
    detail_level: "full"

columns:
  # E-MAIL: удаляем все пробелы внутри, lowercase, валидация по новой регулярке
  email:
    rules:
      - sanitize_invisible: {}   # убираем невидимые символы
      - email_basic:
          pattern: "^[_a-z0-9-]+(\\.[_a-z0-9-]+)*@[a-z0-9-]+(\\.[a-z0-9-]+)*(\\.[a-z]{2,})$"
          on_fail: "clear_cell"
          clear_value: ""

  ip_address:
    rules:
      - ip_basic: {}

  phone:
    rules:
      - sanitize_invisible: {}

  # Префикс (код страны) — опционально, если столбец присутствует
  phone_pfx:
    rules:
      - phone_prefix_basic:
          min_len: 1
          max_len: 3
          validate_cc: true   # строгая проверка через phonenumbers, если установлен

  birthdate:
    rules:
      - birthdate_basic:
          pivot_year: 25      # 00–24 → 2000–2024; 25–99 → 1900–1999

  lastname:
    rules:
      - name_basic: {min_letters: 3}
      - min_length_clear: {min_len: 3}
  firstname:
    rules:
      - name_basic: {min_letters: 3}
      - min_length_clear: {min_len: 3}
  middlename:
    rules:
      - name_basic: {min_letters: 3}
      - min_length_clear: {min_len: 3}
  fullname:
    rules:
      - name_basic: {min_letters: 3}
      - min_length_clear: {min_len: 3}
